name = "Amoni Upsell"
client_id = "e0f1c45c8adddef7b938f848366269b9"
application_url = "https://amonni-upsell-crosssell.vercel.app"
embedded = true

[build]
  automatically_update_urls_on_dev = true
  dev_store_url = "amoni-apps.myshopify.com"
  include_config_on_deploy = true

[access_scopes]
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://amonni-upsell-crosssell.vercel.app/auth/callback",
  "https://amonni-upsell-crosssell.vercel.app/auth/shopify/callback",
  "https://amonni-upsell-crosssell.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2026-07"

[pos]
embedded = false
